[package]
name = "skybox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perlin_noise = "1.0.1"
png = "0.17.7"
